name: Build Document for a given repository

on:
  workflow_dispatch:
    inputs:
      organisation:
        description: "Organisation"
        required: true
        default: "nexi-intra"
      repo:
        description: "Repo"
        required: true
        default: "koksmat-captain"

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      # Define environment variables here
      WORKDIR: ${{ github.workspace }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update Documents
        run: pwsh ./script/documentation/build-docs/run.ps1
        shell: pwsh
